name: Continuous Integration

env:
  ENV_FILE: '.env'
  POETRY_VIRTUALENVS_CREATE: false

on:
  push:
    paths:
      - '**.py'
    branches: [ master, develop ]
  pull_request:
    paths:
      - '**.py'
    branches: [ master, develop ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rule: ["lint", "test"]

    steps:
      - uses: actions/checkout@v3

      - name: Load Env
        run: |
          echo "$GITHUB_WORKSPACE/${{ env.ENV_FILE }}"
          while read line; do
            if [ -n "$line" ]
            then
              echo "$line" >> $GITHUB_ENV
            fi
          done < "$GITHUB_WORKSPACE/${{ env.ENV_FILE }}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dev Deps
        run: |
          make install_dev_deps
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          make install_deps

      - name: Run jobs
        run: |
          make ${{ matrix.rule }}
