name: Continuous Integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Poetry
        env:
          POETRY_HOME: /opt/poetry
          POETRY_VERSION: 1.1.13
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH
          $POETRY_HOME/bin/poetry version
          echo ($POETRY_HOME/bin/poetry version)
          echo $(poetry version)





