name: Continuous Integration

env:
  PYTHON_VERSION: 3.9.10
  POETRY_VIRTUALENVS_CREATE: false

on:
  push:
    paths:
      - '**.py'
    branches: [ master, develop ]
  pull_request:
    paths:
      - '**.py'
    branches: [ master, develop ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rule: ["lint", "test"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dev Deps
        run: |
          make install_dev_deps
          echo "${POETRY_HOME}/bin" >> $GITHUB_PATH
          echo "PATH OUTSIDE = ${PATH}"

      - name: Install Dependencies
        run: |
          echo "PATH OUTSIDE = ${PATH}"
          make install_deps

      - name: Run jobs
        run: |
          make ${{ matrix.rule }}
