name: Test and Coverage

env:
  PYTHON_VERSION: 3.9.10
  POETRY_VIRTUALENVS_CREATE: false

on:
  pull_request:
    paths:
      - '**.py'
    branches: [ master, develop ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
      #
      # Preparation
      #
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Requisites
        run: |
          make install_requisites
          echo "$POETRY_HOME/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          make install_deps

      #
      # Actual jobs
      #
      - name: Run job
        run: |
          make test

      - name: Python Cov
        uses: orgoro/coverage@v2
        with:
          coverageFile: tests/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}








